/*
Deployment script for BandBooker

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


:setvar DatabaseName "BandBooker"
:setvar DefaultFilePrefix "BandBooker"

GO
:on error exit

USE [$(DatabaseName)];

GO
PRINT N'Creating Table [dbo].[Band]...';


GO
CREATE TABLE [dbo].[Band] (
    [BandId]      INT            IDENTITY (1, 1) NOT NULL,
    [Name]        NVARCHAR (50)  NOT NULL,
    [Description] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Band] PRIMARY KEY CLUSTERED ([BandId] ASC)
);


GO
PRINT N'Creating Table [dbo].[BandMusician]...';


GO
CREATE TABLE [dbo].[BandMusician] (
    [BandMusicianId] INT IDENTITY (1, 1) NOT NULL,
    [BandId]         INT NOT NULL,
    [MusicianId]     INT NOT NULL,
    CONSTRAINT [PK_BandMusician] PRIMARY KEY CLUSTERED ([BandMusicianId] ASC)
);


GO
PRINT N'Creating Index [dbo].[BandMusician].[IX_BandMusician_BandId]...';


GO
CREATE NONCLUSTERED INDEX [IX_BandMusician_BandId]
    ON [dbo].[BandMusician]([BandId] ASC);


GO
PRINT N'Creating Index [dbo].[BandMusician].[IX_BandMusician_MusicianId]...';


GO
CREATE NONCLUSTERED INDEX [IX_BandMusician_MusicianId]
    ON [dbo].[BandMusician]([MusicianId] ASC);


GO
PRINT N'Creating Table [dbo].[Booking]...';


GO
CREATE TABLE [dbo].[Booking] (
    [BookingId]   INT            IDENTITY (1, 1) NOT NULL,
    [Name]        NVARCHAR (50)  NOT NULL,
    [Booked]      BIT            NOT NULL,
    [DateBooked]  DATETIME2 (7)  NULL,
    [VenueId]     INT            NULL,
    [DateAndTime] DATETIME2 (7)  NOT NULL,
    [PayOffering] NVARCHAR (MAX) NULL,
    [BandId]      INT            NULL,
    CONSTRAINT [PK_Booking] PRIMARY KEY CLUSTERED ([BookingId] ASC)
);


GO
PRINT N'Creating Index [dbo].[Booking].[IX_Booking_BandId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Booking_BandId]
    ON [dbo].[Booking]([BandId] ASC);


GO
PRINT N'Creating Index [dbo].[Booking].[IX_Booking_VenueId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Booking_VenueId]
    ON [dbo].[Booking]([VenueId] ASC);


GO
PRINT N'Creating Table [dbo].[BookingInstrument]...';


GO
CREATE TABLE [dbo].[BookingInstrument] (
    [BookingInstrumentId] INT IDENTITY (1, 1) NOT NULL,
    [BookingId]           INT NOT NULL,
    [InstrumentId]        INT NOT NULL,
    CONSTRAINT [PK_BookingInstrument] PRIMARY KEY CLUSTERED ([BookingInstrumentId] ASC)
);


GO
PRINT N'Creating Index [dbo].[BookingInstrument].[IX_BookingInstrument_BookingId]...';


GO
CREATE NONCLUSTERED INDEX [IX_BookingInstrument_BookingId]
    ON [dbo].[BookingInstrument]([BookingId] ASC);


GO
PRINT N'Creating Index [dbo].[BookingInstrument].[IX_BookingInstrument_InstrumentId]...';


GO
CREATE NONCLUSTERED INDEX [IX_BookingInstrument_InstrumentId]
    ON [dbo].[BookingInstrument]([InstrumentId] ASC);


GO
PRINT N'Creating Table [dbo].[BookingMusicianInstrument]...';


GO
CREATE TABLE [dbo].[BookingMusicianInstrument] (
    [BookingMusicianInstrumentId] INT            IDENTITY (1, 1) NOT NULL,
    [BookingId]                   INT            NOT NULL,
    [MusicianId]                  INT            NOT NULL,
    [InstrumentId]                INT            NULL,
    [Response]                    BIT            NULL,
    [ResponseDate]                DATETIME       NULL,
    [ResponseReason]              NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_BookingMusicianInstrument] PRIMARY KEY CLUSTERED ([BookingMusicianInstrumentId] ASC)
);


GO
PRINT N'Creating Index [dbo].[BookingMusicianInstrument].[IX_BookingMusicianInstrument_BookingId]...';


GO
CREATE NONCLUSTERED INDEX [IX_BookingMusicianInstrument_BookingId]
    ON [dbo].[BookingMusicianInstrument]([BookingId] ASC);


GO
PRINT N'Creating Index [dbo].[BookingMusicianInstrument].[IX_BookingMusicianInstrument_InstrumentId]...';


GO
CREATE NONCLUSTERED INDEX [IX_BookingMusicianInstrument_InstrumentId]
    ON [dbo].[BookingMusicianInstrument]([InstrumentId] ASC);


GO
PRINT N'Creating Index [dbo].[BookingMusicianInstrument].[IX_BookingMusicianInstrument_MusicianId]...';


GO
CREATE NONCLUSTERED INDEX [IX_BookingMusicianInstrument_MusicianId]
    ON [dbo].[BookingMusicianInstrument]([MusicianId] ASC);


GO
PRINT N'Creating Table [dbo].[Instrument]...';


GO
CREATE TABLE [dbo].[Instrument] (
    [InstrumentId] INT          IDENTITY (1, 1) NOT NULL,
    [Name]         VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_Instrument] PRIMARY KEY CLUSTERED ([InstrumentId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Musician]...';


GO
CREATE TABLE [dbo].[Musician] (
    [MusicianId]  INT             IDENTITY (1, 1) NOT NULL,
    [Name]        NVARCHAR (50)   NOT NULL,
    [Email]       NVARCHAR (50)   NOT NULL,
    [MobilePhone] NVARCHAR (50)   NULL,
    [Bio]         NVARCHAR (4000) NULL,
    [PhotoUrl]    NVARCHAR (255)  NULL,
    CONSTRAINT [PK_Musician] PRIMARY KEY CLUSTERED ([MusicianId] ASC)
);


GO
PRINT N'Creating Table [dbo].[MusicianInstrument]...';


GO
CREATE TABLE [dbo].[MusicianInstrument] (
    [MusicianInstrumentId] INT IDENTITY (1, 1) NOT NULL,
    [MusicianId]           INT NOT NULL,
    [InstrumentId]         INT NOT NULL,
    CONSTRAINT [PK_MusicianInstrument] PRIMARY KEY CLUSTERED ([MusicianInstrumentId] ASC)
);


GO
PRINT N'Creating Index [dbo].[MusicianInstrument].[IX_MusicianInstrument_InstrumentId]...';


GO
CREATE NONCLUSTERED INDEX [IX_MusicianInstrument_InstrumentId]
    ON [dbo].[MusicianInstrument]([InstrumentId] ASC);


GO
PRINT N'Creating Index [dbo].[MusicianInstrument].[IX_MusicianInstrument_MusicianId]...';


GO
CREATE NONCLUSTERED INDEX [IX_MusicianInstrument_MusicianId]
    ON [dbo].[MusicianInstrument]([MusicianId] ASC);


GO
PRINT N'Creating Table [dbo].[Venue]...';


GO
CREATE TABLE [dbo].[Venue] (
    [VenueId]            INT            IDENTITY (1, 1) NOT NULL,
    [Name]               NVARCHAR (50)  NOT NULL,
    [Description]        NVARCHAR (MAX) NULL,
    [ContactName]        NVARCHAR (50)  NULL,
    [ContactEmail]       NVARCHAR (50)  NULL,
    [ContactMobilePhone] NVARCHAR (MAX) NULL,
    [PhotoUrl]           NVARCHAR (MAX) NULL,
    [Address]            NVARCHAR (50)  NULL,
    [Address2]           NVARCHAR (50)  NULL,
    [City]               NVARCHAR (50)  NULL,
    [State]              NVARCHAR (50)  NULL,
    [Zip]                NVARCHAR (20)  NULL,
    [Phone]              NVARCHAR (MAX) NULL,
    [Website]            NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Venue] PRIMARY KEY CLUSTERED ([VenueId] ASC)
);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BandMusician_Band]...';


GO
ALTER TABLE [dbo].[BandMusician] WITH NOCHECK
    ADD CONSTRAINT [FK_BandMusician_Band] FOREIGN KEY ([BandId]) REFERENCES [dbo].[Band] ([BandId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BandMusician_ToMusician]...';


GO
ALTER TABLE [dbo].[BandMusician] WITH NOCHECK
    ADD CONSTRAINT [FK_BandMusician_ToMusician] FOREIGN KEY ([MusicianId]) REFERENCES [dbo].[Musician] ([MusicianId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Booking_ToBand]...';


GO
ALTER TABLE [dbo].[Booking] WITH NOCHECK
    ADD CONSTRAINT [FK_Booking_ToBand] FOREIGN KEY ([BandId]) REFERENCES [dbo].[Band] ([BandId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Booking_ToVenue]...';


GO
ALTER TABLE [dbo].[Booking] WITH NOCHECK
    ADD CONSTRAINT [FK_Booking_ToVenue] FOREIGN KEY ([VenueId]) REFERENCES [dbo].[Venue] ([VenueId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BookingInstrument_Booking]...';


GO
ALTER TABLE [dbo].[BookingInstrument] WITH NOCHECK
    ADD CONSTRAINT [FK_BookingInstrument_Booking] FOREIGN KEY ([BookingId]) REFERENCES [dbo].[Booking] ([BookingId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BookingInstrument_Instrument]...';


GO
ALTER TABLE [dbo].[BookingInstrument] WITH NOCHECK
    ADD CONSTRAINT [FK_BookingInstrument_Instrument] FOREIGN KEY ([InstrumentId]) REFERENCES [dbo].[Instrument] ([InstrumentId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BookingMusicianInstrument_ToBooking]...';


GO
ALTER TABLE [dbo].[BookingMusicianInstrument] WITH NOCHECK
    ADD CONSTRAINT [FK_BookingMusicianInstrument_ToBooking] FOREIGN KEY ([BookingId]) REFERENCES [dbo].[Booking] ([BookingId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BookingMusicianInstrument_ToInstrument]...';


GO
ALTER TABLE [dbo].[BookingMusicianInstrument] WITH NOCHECK
    ADD CONSTRAINT [FK_BookingMusicianInstrument_ToInstrument] FOREIGN KEY ([InstrumentId]) REFERENCES [dbo].[Instrument] ([InstrumentId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BookingMusicianInstrument_ToMusician]...';


GO
ALTER TABLE [dbo].[BookingMusicianInstrument] WITH NOCHECK
    ADD CONSTRAINT [FK_BookingMusicianInstrument_ToMusician] FOREIGN KEY ([MusicianId]) REFERENCES [dbo].[Musician] ([MusicianId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_MusicianInstrument_Instrument]...';


GO
ALTER TABLE [dbo].[MusicianInstrument] WITH NOCHECK
    ADD CONSTRAINT [FK_MusicianInstrument_Instrument] FOREIGN KEY ([InstrumentId]) REFERENCES [dbo].[Instrument] ([InstrumentId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_MusicianInstrument_ToMusician]...';


GO
ALTER TABLE [dbo].[MusicianInstrument] WITH NOCHECK
    ADD CONSTRAINT [FK_MusicianInstrument_ToMusician] FOREIGN KEY ([MusicianId]) REFERENCES [dbo].[Musician] ([MusicianId]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[BandMusician] WITH CHECK CHECK CONSTRAINT [FK_BandMusician_Band];

ALTER TABLE [dbo].[BandMusician] WITH CHECK CHECK CONSTRAINT [FK_BandMusician_ToMusician];

ALTER TABLE [dbo].[Booking] WITH CHECK CHECK CONSTRAINT [FK_Booking_ToBand];

ALTER TABLE [dbo].[Booking] WITH CHECK CHECK CONSTRAINT [FK_Booking_ToVenue];

ALTER TABLE [dbo].[BookingInstrument] WITH CHECK CHECK CONSTRAINT [FK_BookingInstrument_Booking];

ALTER TABLE [dbo].[BookingInstrument] WITH CHECK CHECK CONSTRAINT [FK_BookingInstrument_Instrument];

ALTER TABLE [dbo].[BookingMusicianInstrument] WITH CHECK CHECK CONSTRAINT [FK_BookingMusicianInstrument_ToBooking];

ALTER TABLE [dbo].[BookingMusicianInstrument] WITH CHECK CHECK CONSTRAINT [FK_BookingMusicianInstrument_ToInstrument];

ALTER TABLE [dbo].[BookingMusicianInstrument] WITH CHECK CHECK CONSTRAINT [FK_BookingMusicianInstrument_ToMusician];

ALTER TABLE [dbo].[MusicianInstrument] WITH CHECK CHECK CONSTRAINT [FK_MusicianInstrument_Instrument];

ALTER TABLE [dbo].[MusicianInstrument] WITH CHECK CHECK CONSTRAINT [FK_MusicianInstrument_ToMusician];


GO
PRINT N'Update complete.';


GO
